In [84]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [85]:
dataset = pd.read_csv('wine.csv')
X = dataset.iloc[:, :-1].values
y =  dataset.iloc[:, -1].values

In [86]:
# from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.20, random_state = 0)

# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [87]:
print(X_train)

[[ 0.87668336  0.79842885  0.64412971 ...  0.0290166  -1.06412236
  -0.2059076 ]
 [-0.36659076 -0.7581304  -0.39779858 ...  0.0290166  -0.73083231
  -0.81704676]
 [-1.69689407 -0.34424759 -0.32337513 ...  0.90197362  0.51900537
  -1.31256499]
 ...
 [-0.70227477 -0.68615078 -0.65828065 ...  0.46549511  0.51900537
  -1.31256499]
 [ 1.13777093 -0.62316862 -0.91876272 ... -0.18922266  1.03282752
   0.80164614]
 [ 1.4610222   0.12361993  0.42085937 ... -1.45501034 -1.2168803
  -0.2719767 ]]


In [88]:
print(X_test)

[[ 9.38847070e-01 -6.32166068e-01 -4.35010303e-01 -9.19695615e-01
   1.26324041e+00  5.59998633e-01  9.77754158e-01 -1.20637533e+00
   2.36680192e-02  3.39284695e-01 -1.45574805e-01  8.52295413e-01
   1.04940526e+00]
 [-2.42263344e-01  2.67579163e-01  4.20859365e-01  7.12764102e-01
   8.40672358e-01 -1.27747161e+00 -6.05828120e-01 -9.70634096e-01
  -5.87397203e-01  2.42611713e+00 -2.06608025e+00 -1.55017035e+00
  -8.66598582e-01]
 [-7.64438475e-01 -1.11802849e+00 -7.69915825e-01 -1.61767889e-01
  -9.20027861e-01  2.03653722e+00  1.18341419e+00 -1.36353615e+00
   4.48018868e-01 -2.50930538e-01  1.16386073e+00  3.94021597e-01
  -1.06480588e+00]
 [ 7.15057728e-01 -5.78181354e-01  3.46435916e-01  2.75498106e-01
   1.12238439e+00  1.15061407e+00  8.54358136e-01 -1.28495574e+00
   1.43251284e+00  5.07917619e-01  1.16312302e-01  6.16214963e-01
   1.24761256e+00]
 [ 8.09879269e-02  3.08378173e+00 -8.81550999e-01  5.67008770e-01
  -9.90455870e-01  5.92810602e-01  7.20679112e-01 -4.99151627e-01


In [89]:
# applying the pCA
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [90]:
print(X_train)

[[-2.17884511e+00 -1.07218467e+00]
 [-1.80819239e+00  1.57822344e+00]
 [ 1.09829474e+00  2.22124345e+00]
 [-2.55584748e+00 -1.66210369e+00]
 [ 1.85698063e+00  2.41573166e-01]
 [ 2.58288576e+00 -1.37668170e+00]
 [ 8.72876119e-01  2.25618512e+00]
 [-4.18384029e-01  2.35415681e+00]
 [-3.04977245e-01  2.27659433e+00]
 [ 2.14082532e+00 -1.10052871e+00]
 [-2.98136465e+00 -2.47159183e-01]
 [ 1.96188242e+00  1.25407738e+00]
 [-2.16177795e+00 -9.75966550e-01]
 [ 2.21976084e+00 -2.39507167e+00]
 [-2.30179529e+00 -2.05791962e-01]
 [-3.00953827e+00 -2.79141212e-01]
 [ 2.63443473e+00 -8.68313119e-01]
 [-1.09219965e+00 -3.53906625e+00]
 [ 2.62578435e+00 -2.96852840e-03]
 [ 1.98077342e-01  2.29193443e+00]
 [-2.67442753e+00 -2.58800132e+00]
 [-2.54763698e+00 -4.52703891e-01]
 [ 1.77416736e+00  8.43586940e-01]
 [-2.77786938e+00 -4.32090258e-01]
 [-2.86679938e+00 -1.87580875e+00]
 [ 1.35498845e+00  3.99545184e-02]
 [-2.43900474e+00  9.44074889e-02]
 [-2.27268121e+00  5.05883053e-01]
 [ 1.17887166e+00  2

In [91]:
# applying LogisticRegression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [92]:
# confusion matrics and accuracy
# from sklearn.metrics import confusion_matrix, accuracy_score

# y_pred = classifier.predict(X_test)
# print(confusion_matrix(y_test, y_pred))
# print(accuracy_score(y_test, y_pred))


from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


0.9722222222222222

In [ ]:
# Visuvalization
