In [140]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [141]:
dataset  = pd.read_csv('Wine.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# dataset = pd.read_csv('Wine.csv')
# X = dataset.iloc[:, :-1].values
# y = dataset.iloc[:, -1].values

In [142]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2 , random_state = 0)

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [143]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [144]:
print(X_train)

[[ 0.87668336  0.79842885  0.64412971 ...  0.0290166  -1.06412236
  -0.2059076 ]
 [-0.36659076 -0.7581304  -0.39779858 ...  0.0290166  -0.73083231
  -0.81704676]
 [-1.69689407 -0.34424759 -0.32337513 ...  0.90197362  0.51900537
  -1.31256499]
 ...
 [-0.70227477 -0.68615078 -0.65828065 ...  0.46549511  0.51900537
  -1.31256499]
 [ 1.13777093 -0.62316862 -0.91876272 ... -0.18922266  1.03282752
   0.80164614]
 [ 1.4610222   0.12361993  0.42085937 ... -1.45501034 -1.2168803
  -0.2719767 ]]


In [145]:
# Applying LDA
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
# ida = LDA(n_components =2)
# X_train = ida.fit_transform(X_train, y_train)
# X_test = ida.transform(X_test)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [146]:
print(X_train)

[[-3.57315552  1.94018924]
 [-0.85475898 -2.08182977]
 [-0.62173655 -3.06234453]
 [-4.80786412  2.00638739]
 [ 3.8579759   0.14987256]
 [ 3.59455458  1.24961706]
 [ 0.53772906 -3.0852704 ]
 [-0.04058577 -2.47312446]
 [-0.99835348 -3.36989668]
 [ 3.74095658  1.94844242]
 [-3.76035226  0.82126218]
 [ 0.15106412 -1.86820292]
 [-3.62762899  2.05460026]
 [ 3.94229781  2.80328429]
 [-3.33429017  0.73627798]
 [-3.90206871  1.03276135]
 [ 3.55835472  0.18783108]
 [-5.63175281  2.40524214]
 [ 5.56217254  0.85694946]
 [-0.23296188 -3.94615581]
 [-5.03141997  3.23313754]
 [-3.52861651  0.94605778]
 [ 1.17815662 -2.17294825]
 [-3.58320131  0.67947364]
 [-5.21649905  2.41090952]
 [ 3.01647841  1.24411621]
 [-1.86178658 -0.47484926]
 [-3.93816398 -0.2204059 ]
 [ 1.0836235  -3.32496762]
 [-1.8691488  -0.63362283]
 [-3.27717205  1.51263542]
 [ 0.47842302 -1.16766723]
 [ 4.14433134  1.37391708]
 [-2.45009727 -2.49336285]
 [ 1.20844631 -2.30679956]
 [-2.55631466 -0.98550214]
 [ 1.6091476   0.55066705]
 

In [147]:
# Applying LogisticRegression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
# from sklearn.linear_model import LogisticRegression
# classifier = LogisticRegression(random_state = 0)
# classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [148]:
# coufusion matrix and acuracy
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)
# from sklearn.metrics import confusion_matrix, accuracy_score
# y_pred = classifier.predict(X_test)
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


1.0